// src/app/layout.tsx
import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
	title: "WeMu App",
	description:
		"App that allows users to listen to music playlists, matching the current weather",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body>
				<div className="app-layout">
					{/* Common layout components like header, footer, etc. */}
					{children}
				</div>
			</body>
		</html>
	);
}

// // src/app/layout.tsx
// "use client";

// import React, { Suspense } from "react";
// import { Metadata } from "next";
// import Error from "./api/error";
// import Loading from "./api/loading";
// import { ReactNode, useState, useEffect } from "react";

// export const metadata: Metadata = {
// 	title: "WeMu App",
// 	description:
// 		"App that allows users to listen to music playlists, matching the current weather",
// };

// interface ErrorBoundaryProps {
// 	children: ReactNode;
// }

// function ErrorBoundary({ children }: ErrorBoundaryProps) {
// 	const [hasError, setHasError] = useState(false);
// 	const [error, setError] = useState<Error | null>(null);

// 	useEffect(() => {
// 		const handleError = (event: ErrorEvent) => {
// 			setHasError(true);
// 			setError(event.error);
// 		};
// 		window.addEventListener("error", handleError);
// 		return () => {
// 			window.removeEventListener("error", handleError);
// 		};
// 	}, []);

// 	const resetErrorBoundary = () => {
// 		setHasError(false);
// 		setError(null);
// 	};

// 	if (hasError && error) {
// 		return <Error error={error} reset={resetErrorBoundary} />;
// 	}

// 	return <>{children}</>;
// }

// export default function RootLayout({ children }: { children: ReactNode }) {
// 	return (
// 		<html lang="en">
// 			<body>
// 				<ErrorBoundary>
// 					<Suspense fallback={<Loading />}>
// 						<div className="app-layout">
// 							{/* Common layout components like header, footer, etc. */}
// 							{children}
// 						</div>
// 					</Suspense>
// 				</ErrorBoundary>
// 			</body>
// 		</html>
// 	);
// }

// export default function RootLayout({
// 	children,
// }: {
// 	children: React.ReactNode;
// }) {
// 	return (
// 		<html lang="en">
// 			<body>
// 				<div className="flex flex-col items-center justify-center min-h-screen py-2">
// 					{children}
// 				</div>
// 			</body>
// 		</html>
// 	);
// }

// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   );
// }
